url: https://spencerflaherty.com
branding:
  homeAriaLabel: Spencer Flaherty home
  logoAlt: Spencer Flaherty
  logoDesktopSrc: /static/images/Spencer Flaherty Site Logo v3 - April 22.png
  logoDesktopWidth: 223
  logoDesktopHeight: 180
  logoMobileSrc: /static/images/Spencer Flaherty Site Logo v3 - April 22.png
  logoMobileWidth: 180
  logoMobileHeight: 145
terminal:
  host: root@spencer-portfolio
  rootPath: '~'
  navigationCommand: ./display_categories
  navigationPrompt: Enter module ID
  typeSpeed: 5
  initialDelayMs: 500
layout:
  logoLinkUrl: https://spencerflaherty.com
  paddingAboveLogo: 5px
  paddingBelowLogo: 25px
  paddingBelowWindow: 60px
  windowWidthDesktop: 600px
  windowWidthMobile: 100%
  spacing:
    h1MarginTop: 0px
    h1MarginBottom: 0px
    h2MarginTop: 10px
    h2MarginBottom: 5px
    dropdownMarginBottom: 2px
