url: https://spencerflaherty.com
layout:
  logoLinkUrl: https://spencerflaherty.com
  paddingAboveLogo: 5px
  paddingBelowLogo: 25px
  paddingBelowWindow: 60px
  windowWidthDesktop: 600px
  windowWidthMobile: 100%
  spacing:
    h1MarginTop: 0px
    h1MarginBottom: 0px
    h2MarginTop: 10px
    h2MarginBottom: 5px
    dropdownMarginBottom: 2px
branding:
  logoMobileHeight: 145
  logoMobileWidth: 180
  logoMobileSrc: /static/images/header/logo-mobile.png
  logoDesktopHeight: 180
  logoDesktopWidth: 223
  logoDesktopSrc: /static/images/header/logo-desktop.png
  logoAlt: Spencer Flaherty
  homeAriaLabel: Spencer Flaherty home
terminal:
  host: root@spencer-portfolio
  rootPath: '~'
  navigationCommand: ./display_categories
  navigationPrompt: Enter module ID
  typeSpeed: 5
  initialDelayMs: 500
